export const Assets = {
  welcome:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*gACYRIZ5m0YAAAAAAAAAAAAADgOBAQ/fmt.webp',
  query:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*UhR6QpIWBmIAAAAAAAAAAAAADgOBAQ/fmt.webp',
  spread:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*jpB0Q7Hbm5sAAAAAAAAAAAAADgOBAQ/original',
  styleBtn:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*Ls3WRaRHU30AAAAAAAAAAAAADgOBAQ/original',
  stylePanel:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*4OutRZw69QIAAAAAAAAAAAAADgOBAQ/fmt.webp',
  filterBtn:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*CiM9R73L10cAAAAAAAAAAAAADgOBAQ/original',
  filterPanel:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*QlKsS4gxcT8AAAAAAAAAAAAADgOBAQ/fmt.webp',
  download:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*QjWNRZ-LQ2kAAAAAAAAAAAAADgOBAQ/original',
  end: 'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*-a6uRYo-9qEAAAAAAAAAAAAADgOBAQ/fmt.webp',
  close:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*1qMxQ4fS3e0AAAAAAAAAAAAADgOBAQ/original',
  btnWelcome:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*-0IkQ4wm8TEAAAAAAAAAAAAADgOBAQ/original',
  btnNext:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*T7bRTrLqVcUAAAAAAAAAAAAADgOBAQ/original',
  btnEnd:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*8lvqQr_me34AAAAAAAAAAAAADgOBAQ/original',
  afterStyle:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*x3QnTr_EA2oAAAAAAAAAAAAADgOBAQ/original',
  afterFilter:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*q5jTQ5vZLAQAAAAAAAAAAAAADgOBAQ/original',
  afterSpread:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*k8NSR4y7j40AAAAAAAAAAAAADgOBAQ/original',
  styleGif:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*v8SsRJ0mkFAAAAAAAAAAAAAADgOBAQ/original',
  spreadGif:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*P2nrTLAjhCkAAAAAAAAAAAAADgOBAQ/original',
  queryGif:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*hsYDRLBPUj8AAAAAAAAAAAAADgOBAQ/original',
  filterGif:
    'https://mdn.alipayobjects.com/huamei_qcdryc/afts/img/A*p8zcR7cc0tQAAAAAAAAAAAAADgOBAQ/original',
};
