export const mockDatabaseInfo = {
  baseInfo: [
    { label: '服务器版本号', val: '3.3.3' },
    { label: '运行时间', val: '24小时40分4秒' },
    { label: '服务器代码版本', val: '“Master”' },
    { label: '前端代码版本号', val: '“aef85doster”' },
    { label: 'CPP编译器版本号', val: '“ef85sdjter”' },
    { label: 'Python版本号', val: '“3.5.6”' },
    { label: 'CPP编辑器ID', val: '“GNU”' },
  ],
  configInfo: [
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
    { label: 'bind_host', val: '0.0.0.0' },
  ],
};
